Vagrant.require_version '>= 2.0.0'

Vagrant.configure("2") do |config|
  config.vm.box_download_insecure = true
  config.vm.define "RockyLinux8" do |rl|
    rl.vm.box = "openlogic/rockylinux-8"
    rl.vm.hostname = "rockylinux.dclab.com"
    rl.vm.provider 'virtualbox' do |vb|
      vb.name = "RockyLinux8"
      vb.memory = "1024"
      vb.cpus = "2"
    end
  end
  config.vm.provision 'shell', path: 'provision.sh'
end